services:
  - type: web
    name: gitgood-invoice-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: DYNAMODB_TABLE_NAME
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: API_KEY
        sync: false