openapi: 3.0.0
info:
  title: GitGood Invoice Processing API
  description: >
    A cloud-based REST API for generating, converting, validating, finalising,
    and downloading UBL 2.1 compliant electronic invoices.
  version: 1.0.0

servers:
  - url: https://gitgood-invoice-api.onrender.com/v1
    description: Production (Render)
  - url: http://localhost:3000/v1
    description: Local development

security:
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  schemas:
    Item:
      type: object
      required: [item_name, quantity, unit_price, unit_code, total_price]
      properties:
        item_name:
          type: string
        quantity:
          type: integer
        unit_price:
          type: number
        unit_code:
          type: string
          description: "(example: kg)"
        total_price:
          type: number

    PaymentDetails:
      type: object
      required: [bank_name, account_number, bsb_abn_number, payment_method]
      properties:
        bank_name:
          type: string
        account_number:
          type: string
        bsb_abn_number:
          type: string
        payment_method:
          type: string
          descripton: "(example: bank_transfer)"

    Error:
      type: object
      properties:
        error:
          type: string
          example: "NOT_FOUND"
        message:
          type: string
          example: "Unable to complete"

paths:
  /health:
    get:
      summary: Health check
      description: Returns the current status of the service. No authentication required.
      security: []
      tags: [Health]
      responses:
        '200':
          description: Service is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: down
                  reason:
                    type: string
                    example: "Database connection failed"

  /invoice:
    post:
      summary: Create a new invoice
      description: Creates a new invoice from manually entered data in draft status.
      tags: [Invoice Creation]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - buyer_name
                - buyer_abn
                - supplier_name
                - supplier_abn
                - issue_date
                - payment_due_date
                - items_list
                - tax_rate
                - payment_details
              properties:
                buyer_name:
                  type: string
                buyer_abn:
                  type: string
                supplier_name:
                  type: string
                supplier_abn:
                  type: string
                issue_date:
                  type: string
                  format: date
                payment_due_date:
                  type: string
                  format: date
                items_list:
                  type: array
                  items:
                    $ref: '#/components/schemas/Item'
                tax_rate:
                  type: number
                  description: "(example: 0.1)"
                payment_details:
                  type: array
                  items:
                    $ref: '#/components/schemas/PaymentDetails'
                additional_notes:
                  type: string
      responses:
        '201':
          description: Invoice created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_id:
                    type: string
                  status:
                    type: string
                    example: draft
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Missing or invalid fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INVALID_REQUEST"
                  message: Missing or Invalid Fields
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INTERNAL_SERVER_ERROR"
                  message: Unexpected error on the server side.

    get:
      summary: List all invoices
      description: Returns list of invoices with optional date filters.
      tags: [Invoice Management]
      parameters:
        - in: query
          name: from_date
          schema:
            type: string
            format: date
        - in: query
          name: to_date
          schema:
            type: string
            format: date
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit_per_page
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of Invoices generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoices:
                    type: array
                    items:
                      type: object
                  total:
                    type: integer
                  page:
                    type: integer
        '400':
          description: Invalid filter values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INVALID_REQUEST"
                  message: Missing or Invalid Fields

  /invoice/{invoice_id}:
    get:
      summary: Get a specific invoice
      tags: [Invoice Management]
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invoice details
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_id:
                    type: string
                  status:
                    type: string
                    example: draft
                  buyer_name:
                    type: string
                  supplier_name:
                    typw: string
                  issue_date:
                    type: string
                    format: date
                  payment_due_date:
                    type: string
                    format: date
                  items_list:
                    type: array
                    items:
                     type: object
                  tax_rate: 
                    type: number
                  tax_amount: 
                    type: number
                  tax_payable:
                    type: number
                  ubl_xml: 
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at: 
                    type: string
                    format: date-time

        '404':
          description: Invoice not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "NOT_FOUND"
                  message: Invoice not found
        '400':
          description: Invalid parameter value 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INVALID_REQUEST"
                  message: Missing or Invalid Fields


    put:
      summary: Update an invoice 
      description: Update an invoice using its ID
      tags: [Invoice Management]
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                buyer_name:
                  type: string
                buyer_abn:
                  type: string
                supplier_name:
                  type: string
                supplier_abn:
                  type: string
                issue_date:
                  type: string
                  format: date
                payment_due_date:
                  type: string
                  format: date
                items_list:
                  type: array
                  items:
                    $ref: '#/components/schemas/Item'
                tax_rate:
                  type: number
                payment_details:
                  type: array
                  items:
                    $ref: '#/components/schemas/PaymentDetails'
                additional_notes:
                  type: string
      responses:
        '200':
          description: Invoice updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_id:
                    type: string
                  status:
                    type: string
                    example: draft
                  updated_at:
                    type: string
                    format: date
        '400':
          description: Invalid parameter value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INVALID_REQUEST"
                  message: Missing or Invalid Fields
        '404':
          description: Invoice not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "NOT_FOUND"
                  message: Invoice not found

    delete:
      summary: Delete an invoice
      description: delete an invoice from database
      tags: [Invoice Management]
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invoice deleted Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_id:
                    type: string
                  message:
                    type: string 
                    example: Invoice successfully deleted
        '400':
          description: Invalid parameter value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INVALID_REQUEST"
                  message: Missing or Invalid Fields
        '404':
          description: Invoice not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "NOT_FOUND"
                  message: Invoice not found

  /invoice/{invoice_id}/convert:
    post:
      summary: Convert invoice to UBL XML
      tags: [Invoice Conversion]
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invoice converted to UBL XML Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_id:
                    type: string
                  ubl_xml:
                    type: string 
                  status:
                    type: string 
                    example: "converted"
        '404':
          description: Invoice not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "NOT_FOUND"
                  message: Invoice not found
        '409':
          description: Invoice already converted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "ALREADY_CONVERTED"
                  message: Invoice has already been converted
        '422':
          description: Insufficient data for conversion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INSUFFICIENT_DATA"
                  message: Data is Insufficient for conversion

  /invoice/{invoice_id}/validate:
    post:
      summary: Validate an invoice
      description: Validate an invoice converted to UBL XML format
      tags: [Invoice Validation]
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_id:
                    type: string
                  valid:
                    type: boolean 
                  errors:
                    type: array
                    items:
                     type: object
                    description: "empty if valid"
                  status:
                    type: string
                    example: validated

        '404':
          description: Invoice not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "NOT_FOUND"
                  message: Invoice not found
        '409':
          description: Invoice not yet converted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INVOICE_NOT_CONVERTED"
                  message: Invoice not yet converted

  /invoice/{invoice_id}/final:
    post:
      summary: Finalise a validated invoice
      description: Finalise invoice to be ready to download/email/etc
      tags: [Invoice Finalisation]
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invoice finalised
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice_id:
                    type: string
                  ubl_xml:
                    type: string 
                  status:
                    type: string 
                    example: "finalised"
                  finalised_at:
                    type: string
                    format: date
        '404':
          description: Invoice not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "NOT_FOUND"
                  message: Invoice not found
        '409':
          description: Invoice not yet validated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INVOICE_NOT_VALIDATED"
                  message: Invoice not yet validated

  /invoice/{invoice_id}/download:
    get:
      summary: Download invoice
      description: Download a finalised invoice
      tags: [Invoice Download]
      parameters:
        - in: path
          name: invoice_id
          required: true
          schema:
            type: string
        - in: query
          name: format
          schema:
            type: string
            enum: [xml, json]
            default: xml
      responses:
        '200':
          description: Invoice file downloaded Successfully
        '400':
          description: Invalid format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INVALID_REQUEST"
                  message: Missing or Invalid Fields
        '404':
          description: Invoice not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "NOT_FOUND"
                  message: Invoice not found

        '409':
          description: Invoice not yet finalised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                  error: "INVOICE_NOT_READY"
                  message: Invoice not yet converted/validated