services:
  - type: web
    name: gitgood-invoice-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false